In [1]:
import csv
import numpy as np
ls = []
with open('/home/manik/stock_analysis/Stock_extraction/GOOG_5Y.csv') as csvfile:
    rdr = csv.reader(csvfile)
    for row in rdr:
        ls.append(row)
data = np.array(ls)
data_open = data[1:,1:2]

In [2]:
data_vals = data[1:, 1:].astype(float)

In [3]:
op = data_vals[:, 0:1]
hi = data_vals[:, 1:2]
lo = data_vals[:, 2:3]
cl = data_vals[:, 3:4]
vo = data_vals[:, 4:5]

In [4]:
frac_hi = (hi-op)/op
frac_lo = (op - lo)/op
frac_ch = (cl - op)/op

In [5]:
d = 10

In [6]:
print frac_hi.shape
print frac_lo.shape
print frac_ch.shape

(1257, 1)
(1257, 1)
(1257, 1)


In [7]:
frac_hi = np.reshape(frac_hi,1257)
frac_lo = np.reshape(frac_lo,1257)
frac_ch = np.reshape(frac_ch,1257)

In [8]:
X = np.column_stack([frac_ch, frac_hi, frac_lo])

In [9]:
tr_set = X[0:500]
test_set = X[500:600]

In [10]:
from hmmlearn import hmm
model = hmm.GaussianHMM(n_components=4, covariance_type="diag", n_iter=200)
model.fit(tr_set)

GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=4, n_iter=200, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [11]:
print model.transmat_

[[  1.55998937e-01   1.62326839e-01   1.10414076e-02   6.70632816e-01]
 [  1.00678382e-01   2.62334139e-01   1.95579251e-01   4.41408228e-01]
 [  7.16543059e-07   2.52807011e-03   9.47461470e-01   5.00097436e-02]
 [  3.77556068e-03   2.65099475e-02   6.80020973e-01   2.89693519e-01]]


In [21]:
model.monitor_.converged

True

In [12]:
possible_frac_ch = np.linspace(-0.1, 0.1, 50)
possible_frac_lo = np.linspace(0.0, 0.1, 10)
possible_frac_hi = np.linspace(0.0, 0.1, 10)

In [13]:
def list_of_vals(testing_set, init, window):
    ls = []
    i = init
    while(i < init+window):
        ls.append(testing_set[i])
        i = i+1
    return ls

In [19]:
print model.predict(tr_set)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 3 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 3 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 3 3 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 3 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 3 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 3 3 2 2 2 3 3 2 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [18]:
max_vals = []
for i in range(0,10):
    init = i
    max_score = -1000
    map_val = -1000
    for ch in possible_frac_ch:
        for hi in possible_frac_hi:
            for lo in possible_frac_lo:
                ls = []
                ls = list_of_vals(test_set,init,d)
                ls.append([np.array(ch), np.array(hi), np.array(lo)])
                seq = np.array(ls)
                sc = model.score_samples(seq)
                #print seq.shape
                #print sc
                if(sc > max_score):
                    max_score = sc
                    map_val = [np.array(ch), np.array(hi), np.array(lo)]
                    print model.predict(seq)
    max_vals.append(map_val)
map_vals = np.array(max_vals)
print map_vals

[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2 2 2 3]
[2 2 2 2 2 2 2 2