In [1]:
import numpy as np

In [2]:
cvalues = [32,24,25,28]
c = np.array(cvalues)

In [3]:
print(c)

[32 24 25 28]


In [4]:
print(cvalues)

[32, 24, 25, 28]


In [5]:
f = c+2

In [6]:
print(f)

[34 26 27 30]


In [7]:
l = np.arange(1,10)

In [8]:
print(l)

[1 2 3 4 5 6 7 8 9]


In [9]:
l = np.linspace(1,10,10)
print(l)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [10]:
[samples,step] = np.linspace(1,10,9,retstep = True)

In [11]:
print(samples)

[  1.      2.125   3.25    4.375   5.5     6.625   7.75    8.875  10.   ]


In [12]:
print(step)

1.125


In [13]:
z = []
z.append(samples)

In [14]:
print(z)

[array([  1.   ,   2.125,   3.25 ,   4.375,   5.5  ,   6.625,   7.75 ,
         8.875,  10.   ])]


In [16]:
z = []
z.append(samples[1])

In [17]:
print(z)

[2.125]


In [19]:
z.append('anything')

In [20]:
print(z)

[2.125, 'anything']


#### scalars are 0 dimensional arrays in np

In [21]:
c = np.array(23)

In [22]:
print(np.ndim(c))

0


In [23]:
print(type(c))

<type 'numpy.ndarray'>


In [28]:
v = np.array([1.3,2.5])

In [31]:
print(v.dtype)
print(np.ndim(v))

float64
1


#### 2d and 3d arrays

In [32]:
d2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [33]:
print(d2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(d2.ndim)

2


In [35]:
d3 = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[11,12]]])

In [37]:
print(d3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [38]:
print(d3.ndim)

3


In [40]:
print(d3.shape) #i feel this is like X = 3, Y = 2, Z = 2

(3, 2, 2)


In [41]:
print(d2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(d2.shape)

(3, 3)


In [45]:
d2.shape = (1,9) #size must remain the same

In [44]:
print(d2)

[[1 2 3 4 5 6 7 8 9]]


#### indexing 

In [46]:
print(d2[0][1])

2


In [47]:
print(d2[0,2])

3


In [48]:
print(d2[0])

[1 2 3 4 5 6 7 8 9]


In [52]:
print(d2[0,-1]) #this way is more efficient

9


In [53]:
print(d3[0][1][1])
print(d3[0,0,0])

4
1


#### slicing s[start:stop:step]

In [54]:
s = np.array([0,1,2,3,4,5,6,7,8,9])

In [55]:
s[2:5]

array([2, 3, 4])

In [56]:
s[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
s[:5]

array([0, 1, 2, 3, 4])

In [58]:
s[0:10:2]

array([0, 2, 4, 6, 8])

In [59]:
s[0:8:2]

array([0, 2, 4, 6])

In [60]:
A = np.array([
[11,12,13,14,15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51,52,53,54,55]])

In [61]:
print(A[:3,2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [62]:
print(A[3:,:])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [63]:
x = np.arange(28).reshape(4,7)

In [64]:
print(x)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [65]:
print(x[::2,::3]) #skip every one row and every two columns

[[ 0  3  6]
 [14 17 20]]
